from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from obj_recog.reconstruct import CameraIntrinsics


@dataclass(frozen=True, slots=True)
class CalibrationResult:
    camera_matrix: np.ndarray
    distortion_coefficients: np.ndarray
    image_width: int
    image_height: int
    rms_error: float


def scale_calibration(
    calibration: CalibrationResult,
    *,
    target_width: int,
    target_height: int,
) -> CalibrationResult:
    scale_x = target_width / float(calibration.image_width)
    scale_y = target_height / float(calibration.image_height)
    scaled = np.asarray(calibration.camera_matrix, dtype=np.float32).copy()
    scaled[0, 0] *= scale_x
    scaled[1, 1] *= scale_y
    scaled[0, 2] *= scale_x
    scaled[1, 2] *= scale_y
    return CalibrationResult(
        camera_matrix=scaled,
        distortion_coefficients=np.asarray(calibration.distortion_coefficients, dtype=np.float32).copy(),
        image_width=int(target_width),
        image_height=int(target_height),
        rms_error=float(calibration.rms_error),
    )


def intrinsics_from_calibration(
    calibration: CalibrationResult,
    *,
    target_width: int,
    target_height: int,
) -> CameraIntrinsics:
    scaled = scale_calibration(
        calibration,
        target_width=target_width,
        target_height=target_height,
    )
    matrix = np.asarray(scaled.camera_matrix, dtype=np.float32)
    return CameraIntrinsics(
        fx=float(matrix[0, 0]),
        fy=float(matrix[1, 1]),
        cx=float(matrix[0, 2]),
        cy=float(matrix[1, 2]),
    )


def load_orbslam3_settings(path: str | Path) -> CalibrationResult:
    values: dict[str, float] = {}
    text = Path(path).read_text(encoding="utf-8")
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("%") or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if key.startswith("Camera."):
            try:
                values[key] = float(value)
            except ValueError:
                continue

    required = (
        "Camera.width",
        "Camera.height",
        "Camera.fx",
        "Camera.fy",
        "Camera.cx",
        "Camera.cy",
    )
    missing = [key for key in required if key not in values]
    if missing:
        missing_text = ", ".join(missing)
        raise RuntimeError(f"invalid ORB-SLAM3 settings file, missing: {missing_text}")

    distortion = np.array(
        [
            values.get("Camera.k1", 0.0),
            values.get("Camera.k2", 0.0),
            values.get("Camera.p1", 0.0),
            values.get("Camera.p2", 0.0),
            values.get("Camera.k3", 0.0),
        ],
        dtype=np.float32,
    ).reshape(1, 5)
    camera_matrix = np.array(
        [
            [values["Camera.fx"], 0.0, values["Camera.cx"]],
            [0.0, values["Camera.fy"], values["Camera.cy"]],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float32,
    )
    return CalibrationResult(
        camera_matrix=camera_matrix,
        distortion_coefficients=distortion,
        image_width=int(values["Camera.width"]),
        image_height=int(values["Camera.height"]),
        rms_error=0.0,
    )


def render_orbslam3_settings_yaml(calibration: CalibrationResult, *, fps: float) -> str:
    def _fmt(value: float) -> str:
        value = float(value)
        if value.is_integer():
            return f"{value:.1f}"
        return format(value, ".6g")

    matrix = np.asarray(calibration.camera_matrix, dtype=np.float32)
    dist = np.asarray(calibration.distortion_coefficients, dtype=np.float32).reshape(-1)
    padded_dist = np.pad(dist, (0, max(0, 5 - dist.size)), mode="constant")
    lines = [
        "%YAML:1.0",
        "",
        "# Generated by obj_recog.calibrate",
        "Camera.type: PinHole",
        f"Camera.width: {int(calibration.image_width)}",
        f"Camera.height: {int(calibration.image_height)}",
        f"Camera.fx: {_fmt(matrix[0, 0])}",
        f"Camera.fy: {_fmt(matrix[1, 1])}",
        f"Camera.cx: {_fmt(matrix[0, 2])}",
        f"Camera.cy: {_fmt(matrix[1, 2])}",
        f"Camera.k1: {_fmt(padded_dist[0])}",
        f"Camera.k2: {_fmt(padded_dist[1])}",
        f"Camera.p1: {_fmt(padded_dist[2])}",
        f"Camera.p2: {_fmt(padded_dist[3])}",
        f"Camera.k3: {_fmt(padded_dist[4])}",
        f"Camera.fps: {_fmt(fps)}",
        "Camera.RGB: 1",
        "",
        "ORBextractor.nFeatures: 1200",
        "ORBextractor.scaleFactor: 1.2",
        "ORBextractor.nLevels: 8",
        "ORBextractor.iniThFAST: 20",
        "ORBextractor.minThFAST: 7",
        "",
        "Viewer.KeyFrameSize: 0.05",
        "Viewer.KeyFrameLineWidth: 1.0",
        "Viewer.GraphLineWidth: 0.9",
        "Viewer.PointSize: 2.0",
        "Viewer.CameraSize: 0.08",
        "Viewer.CameraLineWidth: 3.0",
    ]
    return "\n".join(lines) + "\n"
